### ISSUE TITLE
插件报版本依赖冲突了？

### ISSUE THREAD

**Issue by xuexixuexijpg** [xiaojinzi123/KComponent#11]
![image](https://github.com/xiaojinzi123/KComponent/assets/57759182/998a3d8e-ce18-46c1-8ac3-bd2ca9a941f6)
大佬能看下这个吗？emm我都不知道在哪冲突了找不到排除点，关键这两包名group都不一样...

**Comment by xiaojinzi123** [comment]
兄弟 这个很难给你排查耶. 如果插件有问题. 可以不采用插件的方式先用着

**Comment by xuexixuexijpg** [comment]
> 兄弟 这个很难给你排查耶. 如果插件有问题. 可以不采用插件的方式先用着

好了，没事了，多依赖了一个旧的Component了，导致kcomponent-plugin多下了另一个叫KComponent的插件
