### ISSUE TITLE
偶现问题: route fail：router://app/main and errorClass is TargetActivityNotFoundException,errorMsg is 'router://app/main'

### ISSUE THREAD

**Issue by kemioLSC** [xiaojinzi123/KComponent#5]
project clean -> 重新编译就恢复正常了；时不时出现

**Comment by binglingziyu** [comment]
我也经常出现这情况

**Comment by androidcwy** [comment]
遇到过了 +1

**Comment by xiaojinzi123** [comment]
我现在经常遇到这个问题了. 不知道什么原因, 导致 ksp 注解驱动器收集到的被注解标记的元素是空的. 
然后就导致生成了这个模块的服务发现和路由都不会被注册. 而且有时候 clean 项目也没用. 

现在最有效的一个方式是, 找不到的服务发现或者路由所在的模块你随便做一点更新. 让编辑器知道这个模块有内容更新, 就会恢复正常

**Comment by xiaojinzi123** [comment]
我最近有空尽量会看看官方 Room 数据库的 ksp 中的写法, 看看是否有应对之策

**Comment by xiaojinzi123** [comment]
兄弟们, 试试刚 [发布的版本](https://github.com/xiaojinzi123/KComponent/releases/tag/v1.0.8-rc4) 哦. 基本通过骚操作解决了. 
实际上是一个编译的问题. 我也不清楚是 Gradle 批了退还是 ksp 出了轨
但是通过骚操作基本解决了, 大伙多试试哦

**Comment by xiaojinzi123** [comment]
兄弟们 问题还是依然存在. 初步验证是因为 ksp 的增量更新的原因
这篇文章的一处也有描述, 所以兄弟们, 先停用这个配置吧: 
```
# 停用KSP的增量编译
ksp.incremental=false
```
![image](https://github.com/xiaojinzi123/KComponent/assets/12975743/7045b6c4-5a6b-419e-a7f1-a8882779305c)
