### ISSUE TITLE
生成 RouterBean 换行了 This function must return a value of type Intent

### ISSUE THREAD

**Issue by binglingziyu** [xiaojinzi123/KComponent#7]
<img width="1578" alt="image" src="https://github.com/xiaojinzi123/KComponent/assets/6101838/e12a856f-0958-4f5e-8dce-03c5340a9545">

<img width="863" alt="image" src="https://github.com/xiaojinzi123/KComponent/assets/6101838/6336750c-2d96-4c2f-bbbf-655102a600ba">

**Comment by xiaojinzi123** [comment]
换行也不会有啥问题呀 
你每次构建都会报这个错误吗？

**Comment by binglingziyu** [comment]
每次构建都报错，去掉换行就好了

<img width="800" alt="image" src="https://github.com/xiaojinzi123/KComponent/assets/6101838/0b89b962-4f57-4aa8-b53a-c236e4901ecb">


<img width="908" alt="image" src="https://github.com/xiaojinzi123/KComponent/assets/6101838/fe2c390e-4f9a-44c3-b1d3-ca0bacd7516a">

**Comment by binglingziyu** [comment]
写一个超长的方法名就能复现

<img width="1126" alt="image" src="https://github.com/xiaojinzi123/KComponent/assets/6101838/e1becc7d-ba71-42e1-9180-d246271220f9">

**Comment by xiaojinzi123** [comment]
我试试

**Comment by xiaojinzi123** [comment]
确实会出现, 尽量避免下长名称吧
