### ISSUE TITLE
能从Compnent平滑过渡么？

### ISSUE THREAD

**Issue by lotosbin** [xiaojinzi123/KComponent#9]
比如壳工程使用KComponent，功能模块使用Component

**Comment by xiaojinzi123** [comment]
不行 KComponent 是只能支持 Kotlin 的

**Comment by lotosbin** [comment]
已经组件化的工程，如果不能渐进升级，那个升级会是个大工程

**Comment by xiaojinzi123** [comment]
> 已经组件化的工程，如果不能渐进升级，那个升级会是个大工程

因为 KComponent 已经不支持 Java 了, 所以这是没办法的. 除非把原先的需要标记的类都改成 Kotlin 的才可以慢慢过渡
